services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-question-db
    ports:
      - "5435:5432"
    networks:
      - question-service-network
    environment:
      POSTGRES_USER: ${QUESTION_DB_USER}
      POSTGRES_PASSWORD: ${QUESTION_DB_PASSWORD}
      POSTGRES_DB: question-service-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: question-pgadmin
    ports:
      - "8889:80"
    networks:
      - question-service-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres-db
  
  logstash:
    container_name: logstash-question-service
    image: logstash:8.15.0
    ports:
      - "5047:5046"
      - "8001:8080"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - question-service-network
      - flow-overstack_common

networks:
  question-service-network:
  flow-overstack_common:
    external: true
volumes:
  postgres_data:
  redis_data: