services:
  question-service:
    image: maratkk/flow-overstack_question-service:latest
    container_name: question-service
    depends_on:
      - postgres-db
      - logstash
    ports:
      - "8087:8080"
    networks:
      - question-service-network
      - flow-overstack_common
    environment:
      ConnectionStrings__PostgresSQL: Server=postgres-db;Port=5432;Database=question-service-db;User Id=postgres; Password=${QUESTION_DB_PASSWORD}
      Serilog__WriteTo__2__Args__requestUri: http://logstash:8080
      GrpcHosts__UsersHost: http://user-service:8081
      KeycloakSettings__Host: http://keycloak:8080
      KafkaSettings__Host: broker:29092
      AppStartupSettings__KnownProxies: "[]"
      AppStartupSettings__TelemetrySettings__AspireDashboardUrl: http://aspire-dashboard:18889
      AppStartupSettings__TelemetrySettings__JaegerUrl: http://jaeger:4317
      AppStartupSettings__TelemetrySettings__ElasticSearchUrl: http://elasticsearch:9200
      AppStartupSettings__TelemetrySettings__LogstashUrl: http://logstash:8080
      AppStartupSettings__TelemetrySettings__PrometheusUrl: http://prometheus:9090
      AppStartupSettings__TelemetrySettings__AspireDashboardHealthCheckUrl: http://aspire-dashboard:18888
      AppStartupSettings__TelemetrySettings__JaegerHealthCheckUrl: http://jaeger:16686
      AppStartupSettings__TelemetrySettings__UserServiceHealthCheckUrl: http://user-service:8080/health
      RedisSettings__Host: redis
      RedisSettings__Port: 6379
      RedisSettings__Password: ${REDIS_PASSWORD}
  
  postgres-db:
    image: postgres:latest
    container_name: postgres-question-db
    ports:
      - "5435:5432"
    networks:
      - pg-network
      - question-service-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${QUESTION_DB_PASSWORD}
      POSTGRES_DB: question-service-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  logstash:
    container_name: logstash-question-service
    image: logstash:8.15.0
    ports:
      - "5047:5046"
      - "8001:8080"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - question-service-network
      - flow-overstack_common

networks:
  pg-network:
    external: true
  question-service-network:
  flow-overstack_common:
    external: true
volumes:
  postgres_data: