//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionService.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestionService.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сan&apos;t vote for your own post.
        /// </summary>
        public static string CannotVoteForOwnPost {
            get {
                return ResourceManager.GetString("CannotVoteForOwnPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question body is invalid.
        /// </summary>
        public static string InvalidBody {
            get {
                return ResourceManager.GetString("InvalidBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received from cache data is of invalid format.
        /// </summary>
        public static string InvalidCacheDataFormat {
            get {
                return ResourceManager.GetString("InvalidCacheDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format.
        /// </summary>
        public static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagination parametrs are invalid.
        /// </summary>
        public static string InvalidPagination {
            get {
                return ResourceManager.GetString("InvalidPagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag description is invalid.
        /// </summary>
        public static string InvalidTagDescription {
            get {
                return ResourceManager.GetString("InvalidTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name is invalid.
        /// </summary>
        public static string InvalidTagName {
            get {
                return ResourceManager.GetString("InvalidTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question tags are invalid.
        /// </summary>
        public static string InvalidTags {
            get {
                return ResourceManager.GetString("InvalidTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title is invalid.
        /// </summary>
        public static string InvalidTitle {
            get {
                return ResourceManager.GetString("InvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation forbidden.
        /// </summary>
        public static string OperationForbidden {
            get {
                return ResourceManager.GetString("OperationForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found.
        /// </summary>
        public static string QuestionNotFound {
            get {
                return ResourceManager.GetString("QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions not found.
        /// </summary>
        public static string QuestionsNotFound {
            get {
                return ResourceManager.GetString("QuestionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag already exists.
        /// </summary>
        public static string TagAlreadyExists {
            get {
                return ResourceManager.GetString("TagAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not found.
        /// </summary>
        public static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags not found.
        /// </summary>
        public static string TagsNotFound {
            get {
                return ResourceManager.GetString("TagsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too low reputation.
        /// </summary>
        public static string TooLowReputation {
            get {
                return ResourceManager.GetString("TooLowReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found.
        /// </summary>
        public static string UsersNotFound {
            get {
                return ResourceManager.GetString("UsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty.
        /// </summary>
        public static string ValueConnotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueConnotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View not found.
        /// </summary>
        public static string ViewNotFound {
            get {
                return ResourceManager.GetString("ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views not found.
        /// </summary>
        public static string ViewsNotFound {
            get {
                return ResourceManager.GetString("ViewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote already given.
        /// </summary>
        public static string VoteAlreadyGiven {
            get {
                return ResourceManager.GetString("VoteAlreadyGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote not found.
        /// </summary>
        public static string VoteNotFound {
            get {
                return ResourceManager.GetString("VoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes not found.
        /// </summary>
        public static string VotesNotFound {
            get {
                return ResourceManager.GetString("VotesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote type not found.
        /// </summary>
        public static string VoteTypeNotFound {
            get {
                return ResourceManager.GetString("VoteTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote types not found.
        /// </summary>
        public static string VoteTypesNotFound {
            get {
                return ResourceManager.GetString("VoteTypesNotFound", resourceCulture);
            }
        }
    }
}
